export const JOIN_QUIZ_REQUEST = "JOIN_QUIZ_REQUEST";
export const JOIN_QUIZ_SUCCESS = "JOIN_QUIZ_SUCCESS";
export const JOIN_QUIZ_FAIL = "JOIN_QUIZ_FAIL";
export const JOIN_QUIZ_REMOVE = "JOIN_QUIZ_REMOVE";

export const ANSWER_QUESTION = "ANSWER_QUESTION";
export const ANSWER_QUESTION_REMOVE = "ANSWER_QUESTION_REMOVE";

export const FINISH_QUIZ_REQUEST = "FINISH_QUIZ_REQUEST";
export const FINISH_QUIZ_SUCCESS = "FINISH_QUIZ_SUCCESS";
export const FINISH_QUIZ_FAIL = "FINISH_QUIZ_FAIL";

export const CREATE_QUIZ_REQUEST = "CREATE_QUIZ_REQUEST";
export const CREATE_QUIZ_SUCCESS = "CREATE_QUIZ_SUCCESS";
export const CREATE_QUIZ_FAIL = "CREATE_QUIZ_FAIL";

export const ADD_QUESTION = "ADD_QUESTION";
export const CLEAR_QUESTIONS = "CLEAR_QUESTIONS";

export const SUBMIT_QUIZ_REQUEST = "SUBMIT_QUIZ_REQUEST";
export const SUBMIT_QUIZ_SUCCESS = "SUBMIT_QUIZ_SUCCESS";
export const SUBMIT_QUIZ_FAIL = "SUBMIT_QUIZ_FAIL";

export const GET_CREATED_REQUEST = "GET_CREATED_REQUEST";
export const GET_CREATED_SUCCESS = "GET_CREATED_SUCCESS";
export const GET_CREATED_FAIL = "GET_CREATED_FAIL";

export const GET_COMPLETED_REQUEST = "GET_COMPLETED_REQUEST";
export const GET_COMPLETED_SUCCESS = "GET_COMPLETED_SUCCESS";
export const GET_COMPLETED_FAIL = "GET_COMPLETED_FAIL";

export const GET_ATTEMPTS_REQUEST = "GET_ATTEMPTS_REQUEST";
export const GET_ATTEMPTS_SUCCESS = "GET_ATTEMPTS_SUCCESS";
export const GET_ATTEMPTS_FAIL = "GET_ATTEMPTS_FAIL";
